### ISSUE TITLE
I made a windows version for autoinstall and tested with 4090

### ISSUE THREAD

**Issue by sdbds** [microsoft/TRELLIS#10]
Thank you for great work！
It works well！
https://github.com/sdbds/TRELLIS-for-windows/

![Image](https://github.com/user-attachments/assets/fc0db02b-ff80-4c8e-ac49-e310ba1f22d0)
![Image](https://github.com/user-attachments/assets/25475da8-cf5e-4eec-be34-e960ae735567)

Hope to add it to the main repository's README to help more users.

**Comment by sicxu** [comment]
Thanks for your suggestions! Let's move to another issue for better tracking. #3

**Comment by sorc1900** [comment]
1、install-uv-qinglong.ps1    I am not sure what to do with this part?

**Comment by sorc1900** [comment]
powershell run with 2、run_gui.ps1 (right click then choose use powershell run)

What should I see here.  In Powershell I just see 

Windows .venv  and a cursor on the next line?

**Comment by sorc1900** [comment]
@sicxu   Any idea on where to start with this error

Sampling:   0%|                                                                                 | 0/12 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\TRELLIS-for-windows\app.py", line 100, in image_to_3d
    outputs = pipeline.run(
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\TRELLIS-for-windows\trellis\pipelines\trellis_image_to_3d.py", line 281, in run
    coords = self.sample_sparse_structure(cond, num_samples, sparse_structure_sampler_params)
  File "D:\TRELLIS-for-windows\trellis\pipelines\trellis_image_to_3d.py", line 183, in sample_sparse_structure
    z_s = self.sparse_structure_sampler.sample(
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\TRELLIS-for-windows\trellis\pipelines\samplers\flow_euler.py", line 199, in sample
    return super().sample(model, noise, cond, steps, rescale_t, verbose, neg_cond=neg_cond, cfg_strength=cfg_strength, cfg_interval=cfg_interval, **kwargs)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\TRELLIS-for-windows\trellis\pipelines\samplers\flow_euler.py", line 112, in sample
    out = self.sample_once(model, sample, t, t_prev, cond, **kwargs)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\TRELLIS-for-windows\trellis\pipelines\samplers\flow_euler.py", line 73, in sample_once
    pred_x_0, pred_eps, pred_v = self._get_model_prediction(model, x_t, t, cond, **kwargs)
  File "D:\TRELLIS-for-windows\trellis\pipelines\samplers\flow_euler.py", line 43, in _get_model_prediction
    pred_v = self._inference_model(model, x_t, t, cond, **kwargs)
  File "D:\TRELLIS-for-windows\trellis\pipelines\samplers\guidance_interval_mixin.py", line 11, in _inference_model
    pred = super()._inference_model(model, x_t, t, cond, **kwargs)
  File "D:\TRELLIS-for-windows\trellis\pipelines\samplers\flow_euler.py", line 40, in _inference_model
    return model(x_t, t, cond, **kwargs)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\TRELLIS-for-windows\trellis\models\sparse_structure_flow.py", line 192, in forward
    h = block(h, t_emb, cond)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\TRELLIS-for-windows\trellis\modules\transformer\modulated.py", line 156, in forward
    return self._forward(x, mod, context)
  File "D:\TRELLIS-for-windows\trellis\modules\transformer\modulated.py", line 139, in _forward
    h = self.self_attn(h)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\TRELLIS-for-windows\trellis\modules\attention\modules.py", line 126, in forward
    h = scaled_dot_product_attention(q, k, v)
  File "D:\TRELLIS-for-windows\trellis\modules\attention\full_attn.py", line 120, in scaled_dot_product_attention
    out = flash_attn.flash_attn_func(q, k, v)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\flash_attn\flash_attn_interface.py", line 1168, in flash_attn_func
    return FlashAttnFunc.apply(
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\autograd\function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\flash_attn\flash_attn_interface.py", line 815, in forward
    out_padded, softmax_lse, S_dmask, rng_state = _wrapped_flash_attn_forward(
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\_ops.py", line 1116, in __call__
    return self._op(*args, **(kwargs or {}))
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\_library\autograd.py", line 113, in autograd_impl
    result = forward_no_grad(*args, Metadata(keyset, keyword_only_args))
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\_library\autograd.py", line 40, in forward_no_grad
    result = op.redispatch(keyset & _C._after_autograd_keyset, *args, **kwargs)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\_ops.py", line 721, in redispatch
    return self._handle.redispatch_boxed(keyset, *args, **kwargs)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\_library\custom_ops.py", line 324, in backend_impl
    result = self._backend_fns[device_type](*args, **kwargs)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\_compile.py", line 32, in inner
    return disable_fn(*args, **kwargs)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\torch\_library\custom_ops.py", line 367, in wrapped_fn
    return fn(*args, **kwargs)
  File "D:\TRELLIS-for-windows\.venv\lib\site-packages\flash_attn\flash_attn_interface.py", line 96, in _flash_attn_forward
    out, softmax_lse, S_dmask, rng_state = flash_attn_gpu.fwd(
RuntimeError: FlashAttention only supports Ampere GPUs or newer.
Exception raised from mha_fwd at D:\a\flash-attention\flash-attention\csrc\flash_attn\flash_api.cpp:364 (most recent call first):
00007FFAC1C783C900007FFAC1C78320 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFAC1C76BEA00007FFAC1C76B90 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FF998FF430C00007FF998FE5B70 flash_attn_2_cuda.cp310-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FF99900562600007FF998FFC300 flash_attn_2_cuda.cp310-win_amd64.pyd!PyInit_flash_attn_2_cuda [<unknown file> @ <unknown line number>]
00007FF99900573400007FF998FFC300 flash_attn_2_cuda.cp310-win_amd64.pyd!PyInit_flash_attn_2_cuda [<unknown file> @ <unknown line number>]
00007FF998FEE4E500007FF998FE5B70 flash_attn_2_cuda.cp310-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FFAC3004D5600007FFAC3004884 python310.dll!PyList_New [<unknown file> @ <unknown line number>]
00007FFAC3025A5F00007FFAC3021B00 python310.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFAC3020B1700007FFAC3020A90 python310.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFAC2FFE5C800007FFAC2FFE56C python310.dll!PyVectorcall_Call [<unknown file> @ <unknown line number>]
00007FFAC2FFE4A100007FFAC2FFE340 python310.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFAC302776700007FFAC3021B00 python310.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFAC3020B1700007FFAC3020A90 python310.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFAC2FFE5C800007FFAC2FFE56C python310.dll!PyVectorcall_Call [<unknown file> @ <unknown line number>]
00007FFAC2FFE4A100007FFAC2FFE340 python310.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFAC302776700007FFAC3021B00 python310.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFAC3020B1700007FFAC3020A90 python310.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFAC2FFE5C800007FFAC2FFE56C python310.dll!PyVectorcall_Call [<unknown file> @ <unknown line number>]
00007FFAC2FFE4A100007FFAC2FFE340 python310.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFAC302776700007FFAC3021B00 python310.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFAC3020B1700007FFAC3020A90 python310.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFAC2FFE5C800007FFAC2FFE56C python310.dll!PyVectorcall_Call [<unknown file> @ <unknown line number>]
00007FFAC2FFE4A100007FFAC2FFE340 python310.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFAC302776700007FFAC3021B00 python310.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFAC3020B1700007FFAC3020A90 python310.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFAC2FFE5C800007FFAC2FFE56C python310.dll!PyVectorcall_Call [<unknown file> @ <unknown line number>]
00007FFAC2FFE39300007FFAC2FFE340 python310.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF9DC778B2200007FF9DC751770 torch_python.dll!torch::PythonArgParser::raw_parse [<unknown file> @ <unknown line number>]
00007FF9DC774AB800007FF9DC751770 torch_python.dll!torch::PythonArgParser::raw_parse [<unknown file> @ <unknown line number>]
00007FF9DC76BE3400007FF9DC751770 torch_python.dll!torch::PythonArgParser::raw_parse [<unknown file> @ <unknown line number>]
00007FF9DC753D7600007FF9DC751770 torch_python.dll!torch::PythonArgParser::raw_parse [<unknown file> @ <unknown line number>]
00007FF9DBF2F9FB00007FF9DBF2E480 torch_python.dll!c10::ivalue::Future::devices [<unknown file> @ <unknown line number>]
00007FFAC3004D5600007FFAC3004884 python310.dll!PyList_New [<unknown file> @ <unknown line number>]
00007FFAC3047DFC00007FFAC3047C8C python310.dll!PyObject_MakeTpCall [<unknown file> @ <unknown line number>]
00007FFAC3163C3800007FFAC314DE94 python310.dll!Py_gitversion [<unknown file> @ <unknown line number>]
00007FFAC2FFE5C800007FFAC2FFE56C python310.dll!PyVectorcall_Call [<unknown file> @ <unknown line number>]
00007FFAC2FFE4A100007FFAC2FFE340 python310.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFAC302776700007FFAC3021B00 python310.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFAC3020B1700007FFAC3020A90 python310.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFAC301F09E00007FFAC301DCD0 python310.dll!PyObject_GC_Del [<unknown file> @ <unknown line number>]
00007FFAC2FFE5C800007FFAC2FFE56C python310.dll!PyVectorcall_Call [<unknown file> @ <unknown line number>]
00007FFAC2FFE4A100007FFAC2FFE340 python310.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFAC302776700007FFAC3021B00 python310.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFAC3020B1700007FFAC3020A90 python310.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFAC2FFE5C800007FFAC2FFE56C python310.dll!PyVectorcall_Call [<unknown file> @ <unknown line number>]
00007FFAC2FFE4A100007FFAC2FFE340 python310.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFAC302776700007FFAC3021B00 python310.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFAC3020B1700007FFAC3020A90 python310.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFAC2FFE5C800007FFAC2FFE56C python310.dll!PyVectorcall_Call [<unknown file> @ <unknown line number>]
00007FFAC2FFE39300007FFAC2FFE340 python310.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF9DC778AA400007FF9DC751770 torch_python.dll!torch::PythonArgParser::raw_parse [<unknown file> @ <unknown line number>]
00007FF9E2B2CDDC00007FF9E2B2CC70 torch_cpu.dll!c10::Dispatcher::callBoxed [<unknown file> @ <unknown line number>]
00007FF9DC55AC0000007FF9DC55AB50 torch_python.dll!torch::jit::invokeOperatorFromPython [<unknown file> @ <unknown line number>]
00007FF9DC557AE700007FF9DC5579A0 torch_python.dll!torch::jit::_get_operation_for_overload_or_packet [<unknown file> @ <unknown line number>]
00007FF9DC4BEB6600007FF9DC3E4A00 torch_python.dll!registerPythonTensorClass [<unknown file> @ <unknown line number>]
00007FF9DC46836600007FF9DC3E4A00 torch_python.dll!registerPythonTensorClass [<unknown file> @ <unknown line number>]
00007FF9DBF2F9FB00007FF9DBF2E480 torch_python.dll!c10::ivalue::Future::devices [<unknown file> @ <unknown line number>]
00007FFAC3004D5600007FFAC3004884 python310.dll!PyList_New [<unknown file> @ <unknown line number>]
00007FFAC2FFE3E300007FFAC2FFE340 python310.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFAC2FFE4E300007FFAC2FFE340 python310.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFAC302776700007FFAC3021B00 python310.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFAC3020B1700007FFAC3020A90 python310.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFAC304A90800007FFAC304A820 python310.dll!PyObject_FastCallDictTstate [<unknown file> @ <unknown line number>]
00007FFAC31036A700007FFAC3103628 python310.dll!PyObject_Call_Prepend [<unknown file> @ <unknown line number>]
