### ISSUE TITLE
ModuleNotFoundError: No module named 'trellis.representations.mesh.flexicubes.flexicubes'

### ISSUE THREAD

**Issue by jerryao** [microsoft/TRELLIS#102]
run python ./app.py

[SPARSE] Backend: spconv, Attention: flash_attn
Traceback (most recent call last):
  File "/home/jerryao/TRELLIS/app.py", line 12, in <module>
    from trellis.pipelines import TrellisImageTo3DPipeline
  File "/home/jerryao/TRELLIS/trellis/__init__.py", line 3, in <module>
    from . import pipelines
  File "/home/jerryao/TRELLIS/trellis/pipelines/__init__.py", line 2, in <module>
    from .trellis_image_to_3d import TrellisImageTo3DPipeline
  File "/home/jerryao/TRELLIS/trellis/pipelines/trellis_image_to_3d.py", line 15, in <module>
    from ..representations import Gaussian, Strivec, MeshExtractResult
  File "/home/jerryao/TRELLIS/trellis/representations/__init__.py", line 4, in <module>
    from .mesh import MeshExtractResult
  File "/home/jerryao/TRELLIS/trellis/representations/mesh/__init__.py", line 1, in <module>
    from .cube2mesh import SparseFeatures2Mesh, MeshExtractResult
  File "/home/jerryao/TRELLIS/trellis/representations/mesh/cube2mesh.py", line 5, in <module>
    from .flexicubes.flexicubes import FlexiCubes
ModuleNotFoundError: No module named 'trellis.representations.mesh.flexicubes.flexicubes'

**Comment by TherrenceF** [comment]
Yeah U have to downgrade Cuda to 11.8 and install from submodules. 


madamesuperstar#8818 on Discord if you want

**Comment by Sakthi691** [comment]
> run python ./app.py
> 
> [SPARSE] Backend: spconv, Attention: flash_attn Traceback (most recent call last): File "/home/jerryao/TRELLIS/app.py", line 12, in from trellis.pipelines import TrellisImageTo3DPipeline File "/home/jerryao/TRELLIS/trellis/**init**.py", line 3, in from . import pipelines File "/home/jerryao/TRELLIS/trellis/pipelines/**init**.py", line 2, in from .trellis_image_to_3d import TrellisImageTo3DPipeline File "/home/jerryao/TRELLIS/trellis/pipelines/trellis_image_to_3d.py", line 15, in from ..representations import Gaussian, Strivec, MeshExtractResult File "/home/jerryao/TRELLIS/trellis/representations/**init**.py", line 4, in from .mesh import MeshExtractResult File "/home/jerryao/TRELLIS/trellis/representations/mesh/**init**.py", line 1, in from .cube2mesh import SparseFeatures2Mesh, MeshExtractResult File "/home/jerryao/TRELLIS/trellis/representations/mesh/cube2mesh.py", line 5, in from .flexicubes.flexicubes import FlexiCubes ModuleNotFoundError: No module named 'trellis.representations.mesh.flexicubes.flexicubes'

while cloning the git repo use this command - 
git clone --recurse-submodules https://github.com/microsoft/TRELLIS.git

**Comment by NickyDark1** [comment]
colab error
https://github.com/microsoft/TRELLIS/issues/32

**Comment by HengYuD** [comment]
maybe you download .zip，just download https://github.com/MaxtirError/FlexiCubes/tree/f97beb0dd3c6c68f3ab5696b6dcaf9af69f0514e repo and put it in path 
trellis.representations.mesh.flexicubes

**Comment by zade23** [comment]
I encountered the same issue and resolved it by executing these commands:

```
cd TRELLIS
git submodule init
git submodule update
```
