### ISSUE TITLE
How do you specify in the app.py to not use flash_attn ??

### ISSUE THREAD

**Issue by jdc4429** [microsoft/TRELLIS#11]
How do you specify in the app.py to not use flash_attn ?? 

I did not install flash_attn (because it's giving me an error) but it still tries to use it. How do I prevent this?

Error trying to install flash_attn:

(trellis) C:\inetpub\wwwroot\TRELLIS>pip install flash-attn
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting flash-attn
  Downloading flash_attn-2.7.0.post2.tar.gz (2.7 MB)
     ---------------------------------------- 2.7/2.7 MB 8.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jeffc\AppData\Local\Temp\pip-install-34xtqzwr\flash-attn_72812057375a47f494a81dc7ec330502\setup.py", line 162, in <module>
          _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)
        File "C:\Users\jeffc\AppData\Local\Temp\pip-install-34xtqzwr\flash-attn_72812057375a47f494a81dc7ec330502\setup.py", line 82, in get_cuda_bare_metal_version
          raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
        File "C:\Users\jeffc\anaconda3\envs\trellis\lib\subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\jeffc\anaconda3\envs\trellis\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\jeffc\anaconda3\envs\trellis\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\jeffc\anaconda3\envs\trellis\lib\subprocess.py", line 1456, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified

      torch.__version__  = 2.4.0

      [end of output]

**Comment by jdc4429** [comment]
When I add the line os.environ['ATTN_BACKEND'] = 'xformers' to app.py I get the following error... Why does it still try and import flash_attn!!!

(trellis) C:\inetpub\wwwroot\TRELLIS>python app.py
[SPARSE] Backend: spconv, Attention: flash_attn
Warp 1.5.0 initialized:
   CUDA Toolkit 12.6, Driver 12.7
   Devices:
     "cpu"      : "Intel64 Family 6 Model 158 Stepping 9, GenuineIntel"
     "cuda:0"   : "NVIDIA GeForce RTX 2070" (8 GiB, sm_75, mempool enabled)
     "cuda:1"   : "Tesla P40" (24 GiB, sm_61, mempool not supported)
   CUDA peer access:
     Not supported
   Kernel cache:
     C:\Users\jeffc\AppData\Local\NVIDIA\warp\Cache\1.5.0
Warp UserWarning:
   Support for CUDA memory pools was not detected on devices ['cuda:1'].
   This prevents memory allocations in CUDA graphs and may result in poor performance.
   Is the UVM driver enabled?
C:\Users\jeffc\anaconda3\envs\trellis\lib\site-packages\gradio_client\utils.py:1097: UserWarning: file() is deprecated and will be removed in a future version. Use handle_file() instead.
  warnings.warn(
[SPARSE][CONV] spconv algo: auto
[ATTENTION] Using backend: xformers
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\TRELLIS\app.py", line 247, in <module>
    pipeline = TrellisImageTo3DPipeline.from_pretrained("JeffreyXiang/TRELLIS-image-large")
  File "C:\inetpub\wwwroot\TRELLIS\trellis\pipelines\trellis_image_to_3d.py", line 55, in from_pretrained
    pipeline = super(TrellisImageTo3DPipeline, TrellisImageTo3DPipeline).from_pretrained(path)
  File "C:\inetpub\wwwroot\TRELLIS\trellis\pipelines\base.py", line 39, in from_pretrained
    _models = {
  File "C:\inetpub\wwwroot\TRELLIS\trellis\pipelines\base.py", line 40, in <dictcomp>
    k: models.from_pretrained(f"{path}/{v}")
  File "C:\inetpub\wwwroot\TRELLIS\trellis\models\__init__.py", line 59, in from_pretrained
    model = __getattr__(config['name'])(**config['args'], **kwargs)
  File "C:\inetpub\wwwroot\TRELLIS\trellis\models\__init__.py", line 22, in __getattr__
    module = importlib.import_module(f".{module_name}", __name__)
  File "C:\Users\jeffc\anaconda3\envs\trellis\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\inetpub\wwwroot\TRELLIS\trellis\models\structured_latent_vae\__init__.py", line 1, in <module>
    from .encoder import SLatEncoder
  File "C:\inetpub\wwwroot\TRELLIS\trellis\models\structured_latent_vae\encoder.py", line 6, in <module>
    from .base import SparseTransformerBase
  File "C:\inetpub\wwwroot\TRELLIS\trellis\models\structured_latent_vae\base.py", line 7, in <module>
    from ...modules.sparse.transformer import SparseTransformerBlock
  File "C:\inetpub\wwwroot\TRELLIS\trellis\modules\sparse\transformer\__init__.py", line 1, in <module>
    from .blocks import *
  File "C:\inetpub\wwwroot\TRELLIS\trellis\modules\sparse\transformer\blocks.py", line 7, in <module>
    from ..attention import SparseMultiHeadAttention, SerializeMode
  File "C:\inetpub\wwwroot\TRELLIS\trellis\modules\sparse\attention\__init__.py", line 1, in <module>
    from .full_attn import *
  File "C:\inetpub\wwwroot\TRELLIS\trellis\modules\sparse\attention\full_attn.py", line 9, in <module>
    import flash_attn
ModuleNotFoundError: No module named 'flash_attn'

(trellis) C:\inetpub\wwwroot\TRELLIS>

**Comment by JeffreyXiang** [comment]
Hi,

Seems that you add `os.environ['ATTN_BACKEND'] = 'xformers'` after [SPARSE] module is imported, which already setup its backend base on unmodified environ. see
```
[SPARSE] Backend: spconv, Attention: flash_attn
[ATTENTION] Using backend: xformers
```
May you try adding this right after you import os, or just specify it the the command line? like `ATTN_BACKEND=xformers python app.py`.

**Comment by Cey607** [comment]
You can edit the third line of `_init_.py` to run with xformers by default

**Comment by Cey607** [comment]
You can edit the third line of _init_.py to run with xformers by default
@jdc4429

**Comment by FurkanGozukara** [comment]
yes there is a quadro 6000 user : RTX 6000: Turing (TU102)

it doesnt work

how to make it not use flash attention?

**Comment by al3dv2** [comment]
Same problem please helps

**Comment by kexul** [comment]
> Hi,
> 
> Seems that you add `os.environ['ATTN_BACKEND'] = 'xformers'` after [SPARSE] module is imported, which already setup its backend base on unmodified environ. see
> 
> ```
> [SPARSE] Backend: spconv, Attention: flash_attn
> [ATTENTION] Using backend: xformers
> ```
> 
> May you try adding this right after you import os, or just specify it the the command line? like `ATTN_BACKEND=xformers python app.py`.

I can confirm that adding `os.environ['ATTN_BACKEND'] = 'xformers'` right  after os worked.

**Comment by FurkanGozukara** [comment]
I think this should be merged into main repo

 Check if gpu supports flash attention

If not use xformers

**Comment by gmf1982** [comment]
Just need to Write a bat file:
@echo off
call .\venv\Scripts\activate
set ATTN_BACKEND=xformers
python app.py
