### ISSUE TITLE
ModuleNotFoundError: No module named 'diff_gaussian_rasterization' - On Generate

### ISSUE THREAD

**Issue by joseph-schwartz** [microsoft/TRELLIS#12]
Hello Trellis Team,

Amazing Tech!
I installed it on Runpod with 12.2 Cuda and got it installed without issues.  Once I ran the web UI and put an image in, when I hit generate I ran into this:  
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

Any ideas?

Best,
Joe

**Comment by joseph-schwartz** [comment]
Found it, sorry.  Cuda version mismatch, grrrr.  Hard to find a GPU with 11.8: 

Submodule path 'lib/glm': checked out '33b4a621a697a305bc3a7610d290677b96beb181'
Processing /tmp/extensions/diffoctreerast
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diffoctreerast
  Building wheel for diffoctreerast (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-310/diffoctreerast
      copying diffoctreerast/__init__.py -> build/lib.linux-x86_64-cpython-310/diffoctreerast
      copying diffoctreerast/octree_decoupoly_rasterizer.py -> build/lib.linux-x86_64-cpython-310/diffoctreerast
      copying diffoctreerast/octree_gaussian_rasterizer.py -> build/lib.linux-x86_64-cpython-310/diffoctreerast
      copying diffoctreerast/octree_trivec_rasterizer.py -> build/lib.linux-x86_64-cpython-310/diffoctreerast
      copying diffoctreerast/octree_voxel_rasterizer.py -> build/lib.linux-x86_64-cpython-310/diffoctreerast
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/extensions/diffoctreerast/setup.py", line 6, in <module>
          setup(
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
          self.run_command("build")
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 518, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 413, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.4) mismatches the version that was used to compile
      PyTorch (11.8). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diffoctreerast
  Running setup.py clean for diffoctreerast
Failed to build diffoctreerast
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (diffoctreerast)
Cloning into '/tmp/extensions/mip-splatting'...
remote: Enumerating objects: 1672, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 1672 (delta 34), reused 35 (delta 27), pack-reused 1609 (from 1)
Receiving objects: 100% (1672/1672), 21.18 MiB | 88.17 MiB/s, done.
Resolving deltas: 100% (883/883), done.
Processing /tmp/extensions/mip-splatting/submodules/diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff_gaussian_rasterization
  Building wheel for diff_gaussian_rasterization (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-310/diff_gaussian_rasterization
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-310/diff_gaussian_rasterization
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/extensions/mip-splatting/submodules/diff-gaussian-rasterization/setup.py", line 17, in <module>
          setup(
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
          self.run_command("build")
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 518, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/root/miniconda3/envs/trellis/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 413, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.4) mismatches the version that was used to compile
      PyTorch (11.8). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  Running setup.py clean for diff_gaussian_rasterization
Failed to build diff_gaussian_rasterization
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (diff_gaussian_rasterization)
