### ISSUE TITLE
Tryin in Colab

### ISSUE THREAD

**Issue by darkon12** [microsoft/TRELLIS#19]
I'm trying to make it work in Google Colab, I got all the way to make the gradio app work but then I get Error.

Last part of the log is:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/content/TRELLIS/app.py", line 100, in image_to_3d
    outputs = pipeline.run(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/TRELLIS/trellis/pipelines/trellis_image_to_3d.py", line 281, in run
    coords = self.sample_sparse_structure(cond, num_samples, sparse_structure_sampler_params)
  File "/content/TRELLIS/trellis/pipelines/trellis_image_to_3d.py", line 183, in sample_sparse_structure
    z_s = self.sparse_structure_sampler.sample(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/TRELLIS/trellis/pipelines/samplers/flow_euler.py", line 199, in sample
    return super().sample(model, noise, cond, steps, rescale_t, verbose, neg_cond=neg_cond, cfg_strength=cfg_strength, cfg_interval=cfg_interval, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/TRELLIS/trellis/pipelines/samplers/flow_euler.py", line 112, in sample
    out = self.sample_once(model, sample, t, t_prev, cond, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/TRELLIS/trellis/pipelines/samplers/flow_euler.py", line 73, in sample_once
    pred_x_0, pred_eps, pred_v = self._get_model_prediction(model, x_t, t, cond, **kwargs)
  File "/content/TRELLIS/trellis/pipelines/samplers/flow_euler.py", line 43, in _get_model_prediction
    pred_v = self._inference_model(model, x_t, t, cond, **kwargs)
  File "/content/TRELLIS/trellis/pipelines/samplers/guidance_interval_mixin.py", line 11, in _inference_model
    pred = super()._inference_model(model, x_t, t, cond, **kwargs)
  File "/content/TRELLIS/trellis/pipelines/samplers/flow_euler.py", line 40, in _inference_model
    return model(x_t, t, cond, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/TRELLIS/trellis/models/sparse_structure_flow.py", line 192, in forward
    h = block(h, t_emb, cond)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/TRELLIS/trellis/modules/transformer/modulated.py", line 156, in forward
    return self._forward(x, mod, context)
  File "/content/TRELLIS/trellis/modules/transformer/modulated.py", line 139, in _forward
    h = self.self_attn(h)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/TRELLIS/trellis/modules/attention/modules.py", line 126, in forward
    h = scaled_dot_product_attention(q, k, v)
  File "/content/TRELLIS/trellis/modules/attention/full_attn.py", line 120, in scaled_dot_product_attention
    out = flash_attn.flash_attn_func(q, k, v)
  File "/usr/local/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 1163, in flash_attn_func
    return FlashAttnFunc.apply(
  File "/usr/local/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 810, in forward
    out_padded, softmax_lse, S_dmask, rng_state = _wrapped_flash_attn_forward(
  File "/usr/local/lib/python3.10/site-packages/torch/_ops.py", line 1061, in __call__
    return self_._op(*args, **(kwargs or {}))
  File "/usr/local/lib/python3.10/site-packages/torch/_library/autograd.py", line 98, in autograd_impl
    result = Generated.apply(*args, Metadata(keyset, keyword_only_args))  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/site-packages/torch/_library/autograd.py", line 40, in forward
    result = op.redispatch(keyset & _C._after_autograd_keyset, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/_ops.py", line 672, in redispatch
    return self_._handle.redispatch_boxed(keyset, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/_library/custom_ops.py", line 236, in backend_impl
    result = self._backend_fns[device_type](*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 91, in _flash_attn_forward
    out, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
RuntimeError: FlashAttention only supports Ampere GPUs or newer.

Is there a way, in setup.sh or in app.py, not to use FlashAttention (Colab is on T4) ?
Thanks

**Comment by realisticdreamer114514** [comment]
The workaround (if you don't mind not having the Gradio UI) is to open example.py and uncomment line 2
`os.environ['ATTN_BACKEND'] = 'xformers'`
Although you need to add the image path manually at line 17

The README says you can specify installing only xformers in setup.sh by adding --xformers and removing --flash-attn. If you are using it in Colab I suggest installing xformers with the same pip command that installs pytorch, as well as specific kaolin & spconv versions before you run setup.sh, if you don't know that. You can look how to do these up

Tho the option to switch between xformers and flash_attn really should be added to app.py

**Comment by darkon12** [comment]
Edited the third line of trellis\modules\attention\__init__.py
Nothing changed.

**Comment by darkon12** [comment]
Ok, there's probably a cleaner way to do this but I didn't find it so...
The first thing you have to do is completely remove Cuda/Cuda-toolkit as per:
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#removing-cuda-toolkit
Then install cuda-toolkit 11.8 as per:
https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local
Then install conda & clone and setup TRELLIS.
Finally, before executing the last cell, modify app.py adding the line:
os.environ['ATTN_BACKEND'] = 'xformers'
right after 'import os' line.
And change the last line to:
    demo.launch(share=True)
Notebook is here:
https://colab.research.google.com/drive/1CTODdFpY8hcd4Oi9S6Wo3nbh4Ul142o1?usp=drive_link
First two cells take forever and is not exactly lightning fast but it works (finally).

**Comment by Sabrina902-prog** [comment]
👍

**Comment by fahmifahmi11** [comment]
can you please share the colab notebook please?

**Comment by Wakeelfahmed** [comment]
@darkon12  please share the collab notebook

**Comment by darkon12** [comment]
https://github.com/darkon12/TRELLIS-Colab
Didn't check it in months, so I don't know if still working
Let me know
