### ISSUE TITLE
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

### ISSUE THREAD

**Issue by darkon12** [microsoft/TRELLIS#26]
Got stuck at this error in google colab.
Last part of the log is:
Sampling: 100% 12/12 [00:08<00:00,  1.37it/s]
Sampling: 100% 12/12 [00:25<00:00,  2.10s/it]
Rendering: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/content/TRELLIS/app.py", line 115, in image_to_3d
    video = render_utils.render_video(outputs['gaussian'][0], num_frames=120)['color']
  File "/content/TRELLIS/trellis/utils/render_utils.py", line 96, in render_video
    return render_frames(sample, extrinsics, intrinsics, {'resolution': resolution, 'bg_color': bg_color}, **kwargs)
  File "/content/TRELLIS/trellis/utils/render_utils.py", line 73, in render_frames
    res = renderer.render(sample, extr, intr, colors_overwrite=colors_overwrite)
  File "/content/TRELLIS/trellis/renderers/gaussian_render.py", line 223, in render
    render_ret = render(camera_dict, gausssian, self.pipe, self.bg_color, override_color=colors_overwrite, scaling_modifier=self.pipe.scale_modifier)
  File "/content/TRELLIS/trellis/renderers/gaussian_render.py", line 58, in render
    from diff_gaussian_rasterization import GaussianRasterizer, GaussianRasterizationSettings
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

**Comment by YuDeng** [comment]
You can refer to https://github.com/microsoft/TRELLIS/issues/12

**Comment by HardikJain02** [comment]
run these commands:

`find / -name 'diff-gaussian-rasterization' ` to find which folder has these two diff-gaussian-rasterization and simple-knn

`cd tmp/extensions/mip-splatting/submodules` (this is the location i had both of the submodules)

`pip install diff-gaussian-rasterization simple-knn`

**Comment by darkon12** [comment]
> run these commands:
> 
> `find / -name 'diff-gaussian-rasterization' ` to find which folder has these two diff-gaussian-rasterization and simple-knn
> 
> `cd tmp/extensions/mip-splatting/submodules` (this is the location i had both of the submodules)
> 
> `pip install diff-gaussian-rasterization simple-knn`

Already tried, I get:
ERROR: Could not find a version that satisfies the requirement diff-gaussian-rasterization (from versions: none)
ERROR: No matching distribution found for diff-gaussian-rasterization

**Comment by HardikJain02** [comment]
nvcc --version must show cuda 11.8

**Comment by alexdepario** [comment]
Using at home I got this: To create a public link, set `share=True` in `launch()`.
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.83it/s]
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:01<00:00,  6.93it/s]
Rendering: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "F:\TRELLIS\TRELLIS\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "F:\TRELLIS\TRELLIS\venv\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\TRELLIS\TRELLIS\venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "F:\TRELLIS\TRELLIS\venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "F:\TRELLIS\TRELLIS\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "F:\TRELLIS\TRELLIS\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "F:\TRELLIS\TRELLIS\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "F:\TRELLIS\TRELLIS\venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "F:\TRELLIS\TRELLIS\app.py", line 113, in image_to_3d
    video = render_utils.render_video(outputs['gaussian'][0], num_frames=120)['color']
  File "F:\TRELLIS\TRELLIS\trellis\utils\render_utils.py", line 96, in render_video
    return render_frames(sample, extrinsics, intrinsics, {'resolution': resolution, 'bg_color': bg_color}, **kwargs)
  File "F:\TRELLIS\TRELLIS\trellis\utils\render_utils.py", line 73, in render_frames
    res = renderer.render(sample, extr, intr, colors_overwrite=colors_overwrite)
  File "F:\TRELLIS\TRELLIS\trellis\renderers\gaussian_render.py", line 223, in render
    render_ret = render(camera_dict, gausssian, self.pipe, self.bg_color, override_color=colors_overwrite, scaling_modifier=self.pipe.scale_modifier)
  File "F:\TRELLIS\TRELLIS\trellis\renderers\gaussian_render.py", line 58, in render
    from diff_gaussian_rasterization import GaussianRasterizer, GaussianRasterizationSettings
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

**Comment by HardikJain02** [comment]
share your machine specs , do you have gpu, what torch and cuda toolkit versions you are using?

**Comment by darkon12** [comment]
No I didn't.
https://github.com/alexdepario
Another guy
;)

**Comment by Andrey-rmnv** [comment]
Same problem.
nvcc --version showed cuda 11.5, so I upgraded to 11.8, but it didn't help

**Comment by HardikJain02** [comment]
@darkon12 

If you have cuda 11.8 in the machine but nvcc doesn't point to it. [generally below is the location]

```
export PATH=/usr/local/cuda-11.8/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-11.8/lib64:$LD_LIBRARY_PATH
```

if you want to download cuda 11.8 first then repeat above command. and confirm using echo command. use gpt.

```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
sudo apt-get update
sudo apt-get install -y cuda-11-8
```

**Comment by alexdepario** [comment]
> share your machine specs , do you have gpu, what torch and cuda toolkit versions you are using? you switched from colab to windows?

Warp 1.5.0 initialized:
   CUDA Toolkit 12.6, Driver 12.6
   Devices:
     "cpu"      : "Intel64 Family 6 Model 151 Stepping 2, GenuineIntel"
     "cuda:0"   : "NVIDIA GeForce RTX 3090 Ti" (24 GiB, sm_86, mempool enabled)

I'm trying to install and run using this code in a install.bat file: git clone --recurse-submodules https://github.com/microsoft/TRELLIS.git
cd TRELLIS
conda create -n trellis python=3.10
conda activate trellis 

pip install torch==2.5.1 torchvision --index-url=https://download.pytorch.org/whl/cu124
pip install xformers==0.0.28.post3 --index-url=https://download.pytorch.org/whl/cu124
pip install pillow imageio imageio-ffmpeg tqdm easydict opencv-python-headless scipy ninja rembg onnxruntime trimesh xatlas pyvista pymeshfix igraph transformers
pip install git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8
pip install https://github.com/bdashore3/flash-attention/releases/download/v2.7.1.post1/flash_attn-2.7.1.post1+cu124torch2.5.1cxx11abiFALSE-cp310-cp310-win_amd64.whl
pip install kaolin -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.5.1_cu124.html

git clone https://github.com/NVlabs/nvdiffrast.git ./tmp/extensions/nvdiffrast
pip install ./tmp/extensions/nvdiffrast

git clone --recurse-submodules https://github.com/JeffreyXiang/diffoctreerast.git ./tmp/extensions/diffoctreerast
pip install ./tmp/extensions/diffoctreerast

git clone https://github.com/autonomousvision/mip-splatting.git ./tmp/extensions/mip-splatting
pip install ./tmp/extensions/mip-splatting/submodules/diff-gaussian-rasterization/

xcopy /E /H .\extensions\vox2seq\ .\tmp\extensions\vox2seq\
pip install ./tmp/extensions/vox2seq

pip install spconv-cu120
pip install gradio==4.44.1 gradio_litmodel3d==0.0.1

set ATTN_BACKEND=flash-attn
set SPCONV_ALGO=native
python ./app.py

**Comment by DiamondGlassDrill** [comment]
I receive the same error. Are you running other than 4090 gpu? @alexdepario

**Comment by fat-tire** [comment]
If you're using GCC 13, you  may  need to apply [this patch](https://github.com/graphdeco-inria/diff-gaussian-rasterization/pull/49/files).  See [here](https://github.com/graphdeco-inria/gaussian-splatting/issues/788) for more info.

Doing this allowed `./setup.sh --mipgaussian` to complete in a [Linux container](https://hub.docker.com/layers/nvidia/cuda/) with CUDA 12.6.  The file in question, on my system anyway, was at ` /tmp/extensions/mip-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/rasterizer_impl.h`.  It showed up after  `./setup.sh --mipgaussian`  failed to build, but a subsequent attempt post-patch worked.

To install `xformers`, which also had a cuda-incompatibility issue I think, I just manually did `pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu124`  Replace cu124 with your version of cuda. I'm using a rather new one, not 11.8 or whatever.

I think this is all I did to get the demo app working.

**Comment by m0eak** [comment]
> Same problem. nvcc --version showed cuda 11.5, so I upgraded to 11.8, but it didn't help
> 
> UPD: rebooted the system, redo . ./setup.sh --basic --xformers --diffoctreerast --spconv --mipgaussian --kaolin --nvdiffrast problem solved

thanks

**Comment by NaUser** [comment]
https://github.com/autonomousvision/mip-splatting/tree/main     I had the same problem before installing this package. Now everything works great.

**Comment by zxlzxlabs** [comment]
`
#  No module named 'diff_gaussian_rasterization'
apt-get install libglm-dev
git clone https://github.com/autonomousvision/mip-splatting.git
pip install ./mip-splatting/submodules/diff-gaussian-rasterization/
`

**Comment by leonard4** [comment]
Same issue here, no combination of ugrading pip, pytorch, python, cuda etc results in a buildable version of the diff-gaussian .I've cleared the venv, tried just setup.sh --demo, the full setup and nothing works to fix the diff_gaussian_blue module. I also cannot run setup.sh --mipgaussian, I receive the same error as the top guy that the build fails. I feel like theres a step or missing somewhere. Windows 10, whatever stock install the setup.sh runs for all the requirements, 3090 RTX.

![Image](https://github.com/user-attachments/assets/e377fc52-5398-4fcc-a0ef-962fa4404e2d)

**Comment by gganjang** [comment]
For those who have not yet resolved this issue,

The cause of the error "No module named 'diff_gaussian_rasterization' blah~ blah~" is the failed compilation of modules like mipgaussian, diffoctreerast, and nvdiffrast.

Besides mismatched CUDA versions, this error often comes from mismatched compiler versions. I had the same issue on Ubuntu 22.04, and after installing the correct versions of gcc and g++ (For me, 'conda install -c conda-forge gcc_linux-64=11.4.0 gxx_linux-64=11.4.0'), it started building those modules successfully. Eventually, I was able to run the entire demo and generate 3D objects.

**Comment by Kamesh-ed25d004** [comment]
Is there anyway to solve it in windows I have been trying using different cuda versions and trying to match them with torch and diff_gaussian_rasterization but it is not working and I am trying it for free_splatt and mvsgaussian
