### ISSUE TITLE
NameError: name 'FlexiCubes' is not defined

### ISSUE THREAD

**Issue by A7medM0sta** [microsoft/TRELLIS#32]
I have faced these error many times after setting all required libraires i install everything but these error still facing me 

sipython-input-4-e36362159f8f> in <cell line: 13>()
く
# Load a pipeline from a model folder or a Hugging Face model hub.
= TrellisImageTo3DPipeline. from_pretrained ("JeffreyXiang/TRELLIS-image-large")
pipeline. cuda ()
TRELLIS
15
sample_data
5 frames
/content/TRELLIS/trellis/representations/mesh/cube2mesh.py in_init_(self, device, res, use_color)
self.device=device
self. res = res
self mesh_extractor = FlexiCubes(device=device)
self.sdf_bias = -1.0 / res
verts, cube = construct_dense_grid(self.res, self.device)
NameError: name 'FlexiCubes' is not defined

**Comment by YuDeng** [comment]
See if this helps: https://github.com/microsoft/TRELLIS/issues/4

**Comment by A7medM0sta** [comment]
it Still the same error i have following all steps in the read me but nothing change for the error

**Comment by Dan1900** [comment]
maybe you need install kaolin and diso.

**Comment by faisalhrbk** [comment]
got the same error

**Comment by scottmudge** [comment]
You need to install kaolin. Had the same issue at first using a custom venv.

**Comment by A7medM0sta** [comment]
Can you show me the list of libraries and versions you have to use to run as i could modify my setting for it...

**Comment by PladsElsker** [comment]
@A7medM0sta 

I'm using python 3.10.16. 
Again, I had to manually clone and install locally [kaolin](https://github.com/NVIDIAGameWorks/kaolin), as simply running `pip install kaolin` wouldn't work. 

Here's my current `requirements.txt` file after running `pip freeze`, as requested:
```
aiofiles==23.2.1
annotated-types==0.7.0
anyio==4.7.0
asttokens==3.0.0
attrs==24.2.0
blinker==1.9.0
ccimport==0.4.4
certifi==2024.8.30
charset-normalizer==3.4.0
click==8.1.7
coloredlogs==15.0.1
comm==0.2.2
contourpy==1.3.1
cumm-cu120==0.4.11
cycler==0.12.1
dataclasses-json==0.6.7
decorator==5.1.1
Deprecated==1.2.15
diff_gaussian_rasterization @ file:///tmp/extensions/mip-splatting/submodules/diff-gaussian-rasterization
diffoctreerast @ file:///tmp/extensions/diffoctreerast
diso==0.1.4
easydict==1.13
entrypoints==0.4
exceptiongroup==1.2.2
executing==2.1.0
fastapi==0.115.6
ffmpy==0.4.0
filelock==3.16.1
fire==0.7.0
Flask==3.1.0
flatbuffers==24.3.25
fonttools==4.55.2
fsspec==2024.10.0
glcontext==3.0.0
gradio==4.44.1
gradio_client==1.3.0
gradio_litmodel3d==0.0.1
h11==0.14.0
httpcore==1.0.7
httpx==0.28.1
huggingface-hub==0.26.5
humanfriendly==10.0
idna==3.10
igraph==0.11.8
imageio==2.36.1
imageio-ffmpeg==0.5.1
importlib_resources==6.4.5
ipycanvas==0.13.3
ipyevents==2.0.2
ipython==8.30.0
ipywidgets==8.1.5
itsdangerous==2.2.0
jedi==0.19.2
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
jupyter_client==7.4.9
jupyter_core==5.7.2
jupyterlab_widgets==3.0.13
kaolin @ file:///home/plads/Projects/TRELLIS/kaolin
kiwisolver==1.4.7
lark==1.2.2
lazy_loader==0.4
llvmlite==0.43.0
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.23.1
matplotlib==3.9.3
matplotlib-inline==0.1.7
mdurl==0.1.2
moderngl==5.12.0
mpmath==1.3.0
mypy-extensions==1.0.0
nest-asyncio==1.6.0
networkx==3.4.2
ninja==1.11.1.2
numba==0.60.0
numpy==1.26.4
nvdiffrast @ file:///tmp/extensions/nvdiffrast
nvidia-cublas-cu12==12.4.5.8
nvidia-cuda-cupti-cu12==12.4.127
nvidia-cuda-nvrtc-cu12==12.4.127
nvidia-cuda-runtime-cu12==12.4.127
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.4.127
onnxruntime==1.20.1
opencv-python-headless==4.10.0.84
orjson==3.10.12
packaging==24.2
pandas==2.2.3
parso==0.8.4
pccm==0.4.16
pexpect==4.9.0
pillow==10.4.0
platformdirs==4.3.6
plyfile==1.1
pooch==1.8.2
portalocker==3.0.0
prompt_toolkit==3.0.48
protobuf==5.29.1
ptyprocess==0.7.0
pure_eval==0.2.3
pybind11==2.13.6
pydantic==2.10.3
pydantic_core==2.27.1
pydub==0.25.1
pygltflib==1.16.3
Pygments==2.18.0
PyMatting==1.1.13
pymeshfix==0.17.0
pyparsing==3.2.0
python-dateutil==2.9.0.post0
python-multipart==0.0.19
pytz==2024.2
pyvista==0.44.2
PyYAML==6.0.2
pyzmq==26.2.0
referencing==0.35.1
regex==2024.11.6
rembg==2.0.60
requests==2.32.3
rich==13.9.4
rpds-py==0.22.3
ruff==0.8.2
safetensors==0.4.5
scikit-image==0.24.0
scipy==1.14.1
scooby==0.10.0
semantic-version==2.10.0
shellingham==1.5.4
six==1.17.0
sniffio==1.3.1
spconv-cu120==2.3.6
stack-data==0.6.3
starlette==0.41.3
sympy==1.13.1
termcolor==2.5.0
texttable==1.7.0
tifffile==2024.9.20
tokenizers==0.21.0
tomlkit==0.12.0
torch==2.5.1
torchvision==0.20.1
tornado==6.4.2
tqdm==4.67.1
traitlets==5.14.3
transformers==4.47.0
trimesh==4.5.3
triton==3.1.0
typer==0.15.1
typing-inspect==0.9.0
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
usd-core==24.11
utils3d @ git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8
uvicorn==0.32.1
vtk==9.3.1
warp-lang==1.5.0
wcwidth==0.2.13
websockets==12.0
Werkzeug==3.1.3
widgetsnbextension==4.0.13
wrapt==1.17.0
xatlas==0.0.9
xformers==0.0.28.post3

```

**Comment by A7medM0sta** [comment]
thank you very much i appreciate your time

**Comment by VietTralala** [comment]
I was facing the same error `NameError: name 'FlexiCubes' is not defined`. I checked the path `trellis/representations/mesh/flexicubes` and everything was complete. So it was not the problem of not pulling the submodule.

I then manually installed kaolin as suggested by @PladsElsker . The installation process finishes without error. Hwoever when I try it out with `python -c "import kaolin; print(kaolin.__version__)"` I get the following error:

> Traceback (most recent call last):                                                                                                                                                                                                                                              
>   File ".../envs/trellis/lib/python3.10/site-packages/warp/context.py", line 3791, in load_dll                                                                                                                                          
>     dll = ctypes.CDLL(dll_path, winmode=0)                                                                                                                                                                                                                                      
>   File ".../envs/trellis/lib/python3.10/ctypes/__init__.py", line 374, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by .../envs/trellis/lib/python3.10/site-packages/warp/bin/warp.so)                                                                                                   
> 

I dont have admin rights on this machine. Is there some way to solve this?

**Comment by FishWoWater** [comment]
@VietTralala `kaolin` depends on `warp` library, the issue is that you are using pre-built warp that relies on GLIBC_2.29. 
You can try to first builld `warp` from source, according to `https://github.com/NVIDIA/warp`.

**Comment by NickyDark1** [comment]
and tried these ways and i get these errors.

![Image](https://github.com/user-attachments/assets/64f79dd1-d320-4998-a6aa-30d679974eba)

colab 
https://colab.research.google.com/drive/1XnIcTUGmCtt3v0ab5_9ENQEJyY4vtDnZ?usp=sharing

**Comment by DarksealStudios** [comment]
same error.

ModuleNotFoundError: No module named 'trellis.representations.mesh.flexicubes.flexicubes
