### ISSUE TITLE
NameError: name 'FlexiCubes' is not defined

### ISSUE THREAD

**Issue by Cubey42** [microsoft/TRELLIS#4]
Unable to get past this, I've tried installing/building kaolin a couple of different ways but still seems to not be satisfied. not sure what other way to get flexicubes otherwise. I know it says install kaolin and diso but I have also and don't see any sort of error or issue during the install but still get this warning.
```
[SPARSE] Backend: spconv, Attention: flash_attn
Please install kaolin and diso to use the mesh extractor.
Warp 1.5.0 initialized:
   CUDA Toolkit 12.6, Driver 12.7
   Devices:
     "cpu"      : "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel"
     "cuda:0"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
   Kernel cache:
     C:\Users\laser\AppData\Local\NVIDIA\warp\Cache\1.5.0
[SPARSE][CONV] spconv algo: native
[ATTENTION] Using backend: flash_attn
Traceback (most recent call last):
  File "C:\TRELLIS\example.py", line 13, in <module>
    pipeline = TrellisImageTo3DPipeline.from_pretrained("JeffreyXiang/TRELLIS-image-large")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TRELLIS\trellis\pipelines\trellis_image_to_3d.py", line 55, in from_pretrained
    pipeline = super(TrellisImageTo3DPipeline, TrellisImageTo3DPipeline).from_pretrained(path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TRELLIS\trellis\pipelines\base.py", line 40, in from_pretrained
    k: models.from_pretrained(f"{path}/{v}")
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TRELLIS\trellis\models\__init__.py", line 59, in from_pretrained
    model = __getattr__(config['name'])(**config['args'], **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TRELLIS\trellis\models\structured_latent_vae\decoder_mesh.py", line 105, in __init__
    self.mesh_extractor = SparseFeatures2Mesh(res=self.resolution*4, use_color=self.rep_config.get('use_color', False))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TRELLIS\trellis\representations\mesh\cube2mesh.py", line 69, in __init__
    self.mesh_extractor = FlexiCubes(device=device)
                          ^^^^^^^^^^
NameError: name 'FlexiCubes' is not defined
```

**Comment by JeffreyXiang** [comment]
Hi! Did you add `--recurse-submodules` when you do git clone? The FlexiCubes module we use in this code is a git submodule.
See [here](https://github.com/microsoft/TRELLIS/tree/main/trellis/representations/mesh).

If that's the issue, you can run:
```
git submodule init 
git submodule update  
```

**Comment by kexul** [comment]
I cloned the repo by `--recurse-submodules` and I can verify flexicubes folder exists. But the error still triggered.

**Comment by Dan1900** [comment]
The same error!

**Comment by kexul** [comment]
> “Please install kaolin and diso to use the mesh extractor.”
> 
> You need to follow the instructions at https://kaolin.readthedocs.io/en/latest/notes/installation.html to properly install Kaolin.
> 
> I’ve already resolved it.

Yeah, I installed Kaolin correctly and the problem is solved.
